export const path = {
  home: "/",
  login: "/login",
  register: "/register",
  profile: "/profile",
  logout: "/logout",
  verifyTokenEMail: "/auth/verify-token-email/:token",
  loginSocial: "/login-social",
  callBackFacebook: "/auth/facebook/callback",
  callBackGoogle: "/auth/google/callback",
  loginAdmin: "/admin/login",
  registerAdmin: "/admin/register",
  homeAdmin: "/admin",
  managePackage: "/admin/manage-package",
  manageFeature: "/admin/manage-feature",
  manageSalonAdmin: "/admin/manage-salon",
  manageUserAdmin: "/admin/manage-user",
  listSalon: "/listSalon",
  news: "/news",
  detailNew: "/detailNew/:id",
  historyTransaction: "/historyTransaction",
  historyPayment: "/historyPayment",
  postSellCar: "/postSellCar",
  carPostDetail: "/CarPostDetail/:id",
  detailProcess: "/detailProcess/:id",
  historyTransactionDealer: "/historyTransactionDealer",
  promotionDetail: "/promotionDetail/:id",
  salonAppointment: "/salonAppointment",

  satisticDealer: "/satisticDealer",
  myCar: "/myCar",
  //================SALON============================
  salonOto: "/salonOto/:id",
  DetailCar: "/detail-car/:id",
  DetailPackage: "/detail-package/:id",
  ListPackage: "/listPackage",
  booking: "/booking",
  appointment: "/appointment",
  appointmentSalon: "/adminSalon/appointment",
  notificationDetailSalon: "/notification-salon/:id",
  notificationDetailUser: "/notification-user/:id",
  room: "/room/:roomId",
  listMaintenance: "/listMaintenance",
  contact: "/salonOto/contact",
  accessory: "/salonOto/accessory",
  listPromotion: "/salonOto/listPromotion",

  //========ADMIN SALON PATH=====================
  adminSalon: "/adminSalon",
  manageCar: "/adminSalon/manageCar",
  manageSalon: "/adminSalon/manageSalon",
  manageUser: "/adminSalon/manageUser",
  statistic: "/adminSalon/statistic",
  manageGuarantee: "/adminSalon/manageGuarantee",
  manageMaintenance: "/adminSalon/manageMaintenance",
  manageTransaction: "/adminSalon/manageTransaction",
  manageBuyCar: "/adminSalon/manageBuyCar",
  manageBuyMaintenance: "/adminSalon/manageBuyMaintenance",
  manageAccessory: "/adminSalon/manageAccessory",
  manageProcess: "/adminSalon/manageProcess",
  manageStage: "/adminSalon/manageStage",
  processForm: "/adminSalon/processForm",
  manageDealerProcess: "/adminSalon/manageDealerProcess",
  manageAccessoryTransaction: "/adminSalon/manageAccessoryTransaction",
  managePromotion: "/adminSalon/managePromotion",
  managePayment: "/adminSalon/managePayment",
  //============PAYMENT =========================
  getResultPayment: "/payment/vnpay",

  //=================Messgae,Video call==============
  message: "/message",
};
