export const path = {
  home: "/",
  login: "/login",
  register: "/register",
  profile: "/profile",
  logout: "/logout",
  verifyTokenEMail: "/auth/verify-token-email/:token",
  loginSocial: "/login-social",
  callBackFacebook: "/auth/facebook/callback",
  callBackGoogle: "/auth/google/callback",
  listSalon: "/listSalon",
  salonOto: "/salonOto/:id",
  DetailCar: "/detail-car/:id",
  DetailPackage: "/detail-package/:id",
};
